### ISSUE TITLE
Should titles be able to display differently in the archive vs the post?

### ISSUE THREAD

**Issue by richardrissanen** [jarrodtaylor/stationary#7]
Specifically...

If you use subtitles and style the post title with tags the affect is everywhere. Using a small tag for a subtitle in a post would also make that subtitle small in the archive which could be and probably is an undesired effect.

**Comment by jarrodtaylor** [comment]
This may already be possible.  Let's screen share later an try it.

**Comment by richardrissanen** [comment]
Non-issue after discussing
